# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(1, 1))
        self.widget.setStyleSheet("QWidget#widget{ background-color: qlineargradient(spread:pad, x1:0.162489, y1:0.334, x2:0.926475, y2:0.482, stop:0.0956835 rgba(221, 221, 221, 255), stop:0.0978417 rgba(255, 255, 255, 255), stop:0.938849 rgba(254, 254, 254, 255), stop:0.940288 rgba(201, 208, 253, 255)); }")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bottom_widget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.bottom_widget.sizePolicy().hasHeightForWidth())
        self.bottom_widget.setSizePolicy(sizePolicy)
        self.bottom_widget.setMinimumSize(QtCore.QSize(1, 1))
        self.bottom_widget.setObjectName("bottom_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.bottom_widget)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.news_widget = QtWidgets.QWidget(self.bottom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.news_widget.sizePolicy().hasHeightForWidth())
        self.news_widget.setSizePolicy(sizePolicy)
        self.news_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.news_widget.setStyleSheet("")
        self.news_widget.setObjectName("news_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.news_widget)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_summary = marqueelabel(self.news_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_summary.sizePolicy().hasHeightForWidth())
        self.label_summary.setSizePolicy(sizePolicy)
        self.label_summary.setMinimumSize(QtCore.QSize(1, 1))
        self.label_summary.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_summary.setFont(font)
        self.label_summary.setStyleSheet("")
        self.label_summary.setText("")
        self.label_summary.setScaledContents(True)
        self.label_summary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_summary.setWordWrap(True)
        self.label_summary.setObjectName("label_summary")
        self.gridLayout_9.addWidget(self.label_summary, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.news_widget, 0, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.bottom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_10.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.492, y1:0.029, x2:0.476766, y2:0.971, stop:0.0248756 rgba(3, 3, 3, 40), stop:1 rgba(173, 173, 173, 255));")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_4.addWidget(self.widget_10, 0, 1, 1, 1)
        self.clock_widget = QtWidgets.QWidget(self.bottom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clock_widget.sizePolicy().hasHeightForWidth())
        self.clock_widget.setSizePolicy(sizePolicy)
        self.clock_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.clock_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clock_widget.setFont(font)
        self.clock_widget.setObjectName("clock_widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.clock_widget)
        self.gridLayout_10.setContentsMargins(7, 7, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_clock = QtWidgets.QLabel(self.clock_widget)
        self.label_clock.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_clock.setFont(font)
        self.label_clock.setStyleSheet("")
        self.label_clock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_clock.setObjectName("label_clock")
        self.gridLayout_10.addWidget(self.label_clock, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.clock_widget, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.bottom_widget, 1, 0, 1, 1)
        self.upper_widget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(90)
        sizePolicy.setHeightForWidth(self.upper_widget.sizePolicy().hasHeightForWidth())
        self.upper_widget.setSizePolicy(sizePolicy)
        self.upper_widget.setMinimumSize(QtCore.QSize(1, 1))
        self.upper_widget.setStyleSheet("")
        self.upper_widget.setObjectName("upper_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.upper_widget)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(7)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.upper_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(97)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.video_widget = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_widget.sizePolicy().hasHeightForWidth())
        self.video_widget.setSizePolicy(sizePolicy)
        self.video_widget.setMinimumSize(QtCore.QSize(1, 1))
        self.video_widget.setObjectName("video_widget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.video_widget)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.stackedWidget = QtWidgets.QStackedWidget(self.video_widget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1, 1))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("movie_poster.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.video_player = QVideoWidget(self.page_2)
        self.video_player.setMinimumSize(QtCore.QSize(1, 1))
        self.video_player.setAutoFillBackground(True)
        self.video_player.setObjectName("video_player")
        self.gridLayout_24.addWidget(self.video_player, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_23.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.video_widget, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_7.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.492, y1:0.029, x2:0.476766, y2:0.971, stop:0.0248756 rgba(3, 3, 3, 40), stop:1 rgba(173, 173, 173, 255));")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_5.addWidget(self.widget_7, 0, 1, 1, 1)
        self.weather_widget = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weather_widget.sizePolicy().hasHeightForWidth())
        self.weather_widget.setSizePolicy(sizePolicy)
        self.weather_widget.setMinimumSize(QtCore.QSize(1, 1))
        self.weather_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.weather_widget.setObjectName("weather_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.weather_widget)
        self.gridLayout_6.setContentsMargins(0, -1, 0, 30)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_12 = QtWidgets.QWidget(self.weather_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_logo = aspect_label(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setMinimumSize(QtCore.QSize(1, 1))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout_7.addWidget(self.label_logo, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_12, 0, 0, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.weather_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_15 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_22.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_location1 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_location1.setFont(font)
        self.label_location1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_location1.setObjectName("label_location1")
        self.gridLayout_22.addWidget(self.label_location1, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget_15, 0, 0, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_2 = QtWidgets.QWidget(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(1, 1))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setStyleSheet("")
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_19)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_6 = aspect_label(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(1, 1))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("weather.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_17.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_19, 0, 1, 1, 1)
        self.widget_20 = QtWidgets.QWidget(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_temp1 = QtWidgets.QLabel(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_temp1.sizePolicy().hasHeightForWidth())
        self.label_temp1.setSizePolicy(sizePolicy)
        self.label_temp1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.label_temp1.setFont(font)
        self.label_temp1.setStyleSheet("")
        self.label_temp1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp1.setObjectName("label_temp1")
        self.gridLayout_19.addWidget(self.label_temp1, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_20, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setMinimumSize(QtCore.QSize(1, 1))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_20.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_3, 0, 3, 1, 1)
        self.gridLayout_11.addWidget(self.widget_16, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_13, 1, 0, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.weather_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_12.setVerticalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_17 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_location2 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        self.label_location2.setFont(font)
        self.label_location2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_location2.setObjectName("label_location2")
        self.gridLayout_14.addWidget(self.label_location2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_17, 0, 0, 1, 1)
        self.widget_18 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_18)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_5 = QtWidgets.QWidget(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setMinimumSize(QtCore.QSize(1, 1))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_26.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_23 = QtWidgets.QWidget(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setAutoFillBackground(False)
        self.widget_23.setStyleSheet("")
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_23)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_7 = aspect_label(self.widget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(1, 1))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("weather.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_23, 0, 1, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setStyleSheet("")
        self.widget_24.setObjectName("widget_24")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget_24)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_temp2 = QtWidgets.QLabel(self.widget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_temp2.sizePolicy().hasHeightForWidth())
        self.label_temp2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.label_temp2.setFont(font)
        self.label_temp2.setStyleSheet("c")
        self.label_temp2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp2.setObjectName("label_temp2")
        self.gridLayout_21.addWidget(self.label_temp2, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_24, 0, 2, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setMinimumSize(QtCore.QSize(1, 1))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_25.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_8, 0, 3, 1, 1)
        self.gridLayout_12.addWidget(self.widget_18, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_14, 3, 0, 1, 1)
        self.label_text1 = QtWidgets.QLabel(self.weather_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text1.setFont(font)
        self.label_text1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_text1.setObjectName("label_text1")
        self.gridLayout_6.addWidget(self.label_text1, 2, 0, 1, 1)
        self.label_text2 = QtWidgets.QLabel(self.weather_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text2.setFont(font)
        self.label_text2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_text2.setObjectName("label_text2")
        self.gridLayout_6.addWidget(self.label_text2, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.weather_widget, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.upper_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 10))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 10))
        self.widget_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.019, y1:0.557, x2:0.984229, y2:0.562, stop:0.0248756 rgba(3, 3, 3, 40), stop:1 rgba(173, 173, 173, 255))")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.upper_widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "cb infoskjerm"))
        self.label_clock.setText(_translate("MainWindow", "Initializing..."))
        self.label_location1.setText(_translate("MainWindow", "Initializing..."))
        self.label_temp1.setText(_translate("MainWindow", "0"))
        self.label_location2.setText(_translate("MainWindow", "Initializing..."))
        self.label_temp2.setText(_translate("MainWindow", "0"))
        self.label_text1.setText(_translate("MainWindow", "Savak vind"))
        self.label_text2.setText(_translate("MainWindow", "Savak vind"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
from marqueelabel import marqueelabel
from testing import aspect_label


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
